# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Offense count: 32
Metrics/AbcSize:
  Max: 405

# Offense count: 3
Metrics/BlockNesting:
  Max: 4

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1283

# Offense count: 20
Metrics/CyclomaticComplexity:
  Max: 24

# Offense count: 43
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 169

# Offense count: 40
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 314

# Offense count: 8
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 577

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 19
Metrics/PerceivedComplexity:
  Max: 28

